sudo: required
services:
  - docker

before_install:
  - docker build -t egonzal93/docker-epsilon11 -f Dockerfile.dev .

script:
  - docker run -t egonzal93/docker-epsilon11 npm run test -- --coverage