sudo: required
services:
  - docker

before_install:
  - docker build -t egonzal93/docker-epsilon11 -f Dockerfile.dev .

script:
  - docker run -t egonzal93/docker-epsilon11 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-epsilon11"
  env: "DockerEpsilon11-env"
  bucket_name: "elasticbeanstalk-us-east-2-837134779439"
  bucket_path: "docker-epsilon11"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
